"""Plan schema for RUNE LLM outputs.

Ported from src/llm/schemas/plan.ts - Pydantic equivalents of the Zod
Step / RollbackPlan / Plan schemas used for structured plan generation.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class StepSchema(BaseModel):
    """A single execution step within a plan."""

    step_id: int = Field(alias="stepId", description="Unique step identifier")
    tool: str = Field(description="Tool to use (file, browser, process, network, git)")
    action: str = Field(description="Action to perform")
    params: dict[str, Any] = Field(default_factory=dict, description="Parameters for the action")
    depends_on: list[int] = Field(
        default_factory=list, alias="dependsOn",
        description="Step IDs this step depends on",
    )
    timeout_ms: int = Field(default=60_000, alias="timeoutMs", description="Timeout in milliseconds")
    expected_output: str | None = Field(
        default=None, alias="expectedOutput",
        description="Description of expected output",
    )

    model_config = ConfigDict(populate_by_name=True)


class RollbackPlanSchema(BaseModel):
    """Rollback plan attached to a Plan."""

    strategy: Literal["move_back", "delete", "restore", "none"] = Field(
        description="Rollback strategy",
    )
    steps: list[StepSchema] = Field(default_factory=list, description="Rollback steps")
    data: dict[str, Any] = Field(default_factory=dict, description="Data needed for rollback")
    persistent: bool = Field(default=True, description="Whether rollback survives session")
    expires_at: str | None = Field(
        default=None, alias="expiresAt",
        description="ISO date when rollback expires",
    )

    model_config = ConfigDict(populate_by_name=True)


class PlanSchema(BaseModel):
    """Top-level plan generated by the planner LLM."""

    plan_id: str = Field(alias="planId", description="Unique plan identifier")
    created_at: str = Field(alias="createdAt", description="ISO date when plan was created")
    intent_summary: str = Field(alias="intentSummary", description="Summary of what the plan does")
    steps: list[StepSchema] = Field(description="Execution steps")
    risk: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(description="Risk level")
    confidence: float = Field(ge=0, le=1, description="Confidence score 0-1")
    requires_approval: bool = Field(alias="requiresApproval", description="Whether user approval is needed")
    rollback: RollbackPlanSchema = Field(description="Rollback plan")
    estimated_duration_ms: int = Field(alias="estimatedDurationMs", description="Estimated duration in milliseconds")

    model_config = ConfigDict(populate_by_name=True)


def parse_plan_from_llm(llm_plan: PlanSchema) -> dict[str, Any]:
    """Convert an LLM-generated PlanSchema into an internal dict with datetime objects."""
    data = llm_plan.model_dump(by_alias=False)
    data["created_at"] = datetime.fromisoformat(llm_plan.created_at)
    if llm_plan.rollback.expires_at:
        data["rollback"]["expires_at"] = datetime.fromisoformat(llm_plan.rollback.expires_at)
    return data
